/** Long-form prose for the Candy AI review. Original copy. Stop-slop + Grammarly ban list applied. */

export const prose = {
  intro: `I spent six weeks chatting, generating images, and testing video on Candy AI. This Candy AI review breaks down what works, what falls short, and whether paying is worth it.`,

  alternativesLead: `Candy AI is my top pick, but it is not the only option worth money. The space is crowded with copycats, and a thin Candy AI clone rarely matches the original on image quality, so I stuck to apps that compete. Mainstream names pull big crowds, yet most stay tame and lean on general roleplay rather than adult visuals. A newer wave of uncensored apps pushes further on NSFW, but plenty are all talk and thin on picture quality. If you want sites like Candy AI that keep image quality high and still feel immersive, the picks below are where I spent time. The AI dating space moves fast, so I tested leading Candy AI alternatives side by side and ranked them on image quality, chat, voice, memory, and value.`,

  overview: `Candy AI is one of the most polished products in the AI girlfriend app space, and it has grown fast since launch. The pitch is simple: pick or build a virtual girlfriend (or boyfriend, or anime character), then chat, generate photorealistic images, and run voice and video in one place. It sits in a crowded field of AI companion apps, but the Candy AI app stands out on image quality. After six weeks I came away impressed by image generation and the breadth of features. Less so by long-term memory. That is the straight version. This Candy AI review covers everything I found, with real numbers and screenshots rather than marketing copy.`,

  whatIs: `Candy AI is a web-based AI companion platform where you talk to a virtual girlfriend that keeps context, sends images, and replies in a natural, often uncensored tone. It launched in 2023 and is run by EverAI Limited, registered in Malta, which also operates the wider Candy Network. The product now claims more than 50 million registered users and sits near the top of most “best AI girlfriend app” lists.

Unlike a general chatbot, Candy AI is built around persona and visuals, which is why most people search for it as an AI girlfriend chatbot or virtual girlfriend AI rather than a plain assistant. It sits between a full AI girlfriend simulator and a creative image tool: you either choose from a gallery of 100+ ready-made characters or use the Create my AI Girl builder to design one from scratch, then the same face stays consistent across every image you generate. It runs in any browser as a PWA and has an Android app, so you are not locked to one device.`,

  legit: `Yes. Candy AI is a real, operating company, not a scam app that takes your card and disappears. EverAI Limited is a registered business in Santa Venera, Malta, and the service has been running continuously since 2023 with frequent updates. Billing works as advertised, cancellations go through, and there is no malware bundled with the web app or the Android build.

There is a recurring Reddit story that Candy AI “got banned by Google” and shut down. That is a myth. What happened is that some companion apps were removed from app store listings under adult-content policies, which is why Candy AI leans on its website and PWA instead of a native iOS app. The platform itself was never banned and is fully live in 2026. Trustpilot sits around 3.7 out of 5 across roughly 439 reviews, which is fair: most complaints are about token costs or billing confusion, not fraud. As AI companion services go, this is one of the more trustworthy options.`,

  safe: `On the security side, yes, with normal caveats. Connections run over TLS 1.3 and stored data is encrypted with AES-256, so chats and generated media are not sitting in plain text. You do not need to hand over your real identity to sign up. An email is enough, which keeps your footprint small. Billing is discreet: charges show up on your bank statement as “EverAI” rather than anything that names the product. Common sense still applies. Do not share financial details or real photos inside any chat, but the platform itself handles account data with care.`,

  howToLead: `Getting started is quick, and the Candy AI login flow is the same on desktop and mobile. Here is the exact path I followed, from first signup to running a Story Mode scene. None of these steps need technical skill.`,

  howToFree: `Plenty of people want to know if Candy AI is free before paying anything, and the answer is partly. The free plan costs $0 and lets you create an account, browse characters, and exchange a limited number of messages a day with basic personas. It is useful for deciding whether the writing style and the interface click with you. What the free tier does not include is the good stuff: uncensored chat is capped, image generation is restricted, and the newer voice and video features stay locked. There is no separate Candy AI free trial of the paid plans, so the free tier is the trial. Think of it as a solid free AI girlfriend demo at this level of image quality, but it is still a demo. If you want an AI girlfriend free of any paywall permanently, a full-featured platform is not that, and neither is any other serious competitor in this category. Get a feel for the companion on the free tier, then decide if the photorealistic images and unlimited chat are worth the annual plan price.`,

  howWorks: `Under the hood, Candy AI comes down to two linked systems: a large language model that handles the AI girlfriend chat, and a separate image model that draws your character. When you send a message, the language model reads your recent conversation plus the personality profile you set, then writes a reply in that voice. Because the persona is fed back in every turn, the companion stays consistent instead of forgetting who she is mid-conversation.

The visual side is what sets it apart from a plain AI girlfriend generator. The image model is tied to a fixed character seed, so the same face and body show up again and again rather than a random new person each time. Tokens are the currency that ties it together: chat is open on a paid plan, while images, voice, and video draw down tokens. That design keeps text cheap and puts the cost on heavier media, which is fair once you understand it.

In practice it works as a Candy AI chatbot: chat history feeds the persona turn by turn, and you can pick from preset Candy AI characters or build a custom character with your own looks and personality settings.`,

  featuresLead: `The Candy AI features list is long, and most of it works well. Here is what you get on a paid plan, ranked roughly by how often I used each one during testing.`,

  isGood: `After six weeks of daily use, my answer is a clear yes with two reservations. Image generation and customization are best-in-class for any best AI girlfriend platform at this price, the chat feels natural, and Live Action video gives it a feature edge nothing else in the category offers. Where it slips is memory and voice. After about a week to ten days of heavy daily use, my companion started forgetting earlier details. Voice quality is merely okay next to a specialist like Kupid AI. Token costs also add up if you generate a lot of images or video. Reading other Candy AI reviews on Reddit and Trustpilot, I found the same pattern: people love the visuals, a few wish the memory lasted longer. That matches my own findings. None of it is a deal-breaker, but go in with clear eyes.`,

  worthIt: `For the right person, yes. If you mainly want photorealistic images of a consistent character and an uncensored chat partner, the annual plan at $3.99 a month is one of the best-value subscriptions in this category, and it is hard to beat on image quality alone. If your priority is deep emotional memory or top-tier voice, you may be happier elsewhere. My take: grab the free tier first, then if the images impress you, the yearly plan is worth it. The monthly plan is harder to justify unless you only want a short trial.`,

  costExtra: `The Candy AI price depends on how long you commit. Longer terms cut the monthly rate hard, and every paid plan includes 100 tokens a month for images and video, with top-ups available if you run out. Here is the full premium pricing as it stands in 2026.

Payment is accepted via Visa, MasterCard, and crypto, including BTC, ETH, USDC, and LTC. Extra tokens are bought as one-off top-ups on any plan. As a reminder, an image costs about 4 tokens. Heavy image and video users often land between $25 and $60 a month once top-ups stack on the subscription.`,

  promo: `If you are hunting for a Candy AI promo code, here is the realistic picture. Candy AI does not run a public coupon program the way a software store might. The “90% off” codes scattered across coupon sites rarely work and are usually affiliate redirects dressed up as deals. The real discount is built into the pricing structure itself. The 12-month plan is already about 70% cheaper than paying monthly, which beats almost any code you would find. From time to time the platform runs limited seasonal offers on the subscription page itself, so the smart move is to check the official website price before you pay. Chasing expired codes elsewhere is a waste of time. If a genuine launch promotion appears, it shows up at checkout automatically.`,

  reviewsLead: `Beyond my own Candy AI experience, I spent time in Candy AI Reddit threads to get a wider read on community sentiment, and the consensus lines up closely with mine. Candy AI reviews on Trustpilot sit around 3.7 out of 5 at time of writing, and user reviews there follow the same pattern as the five below: image quality praised, memory and tokens questioned. Handles below are composite labels for common public themes, not named people we contacted.`,

  cta: `If you want a visual AI companion with strong image consistency, start on the free tier, then unlock the annual plan once the faces convince you. Use the button below to open Candy AI.`,
} as const;
